### ISSUE TITLE
Manifest version 3 update checklist

### ISSUE THREAD

**Issue by Skeletonxf** [Skeletonxf/duplicate-tab#19]
- [x] Duplicate Tab uses a persistent background page, this will need migrating to a non persistent one. Duplicate Tab has very little state in that background page so this should be straightforward.
- [x] Browser action APIs have changed namespace. Since the APIs are the same this should be a trivial update.
- [x] This migration is a good opportunity to adopt newer JavaScript language features than ES6: `async`/`await`/`??`/`?.`
- [x] The minimum supported Firefox version will need increasing to whatever version of FF ships MV3 first, regardless of which version this is, it should be more than new enough for adopting modern JavaScript language features.
- [x] Session storage comes in at FF 115, this is the absolute minimum to port all functionality without risking stale tab ID bugs
- [x] Revisit https://github.com/Skeletonxf/duplicate-tab/issues/14?
- ~~[ ] Revisit https://github.com/Skeletonxf/duplicate-tab/issues/8 (it may be possible by combining [`executeScript`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/executeScript) with [`history.back()`](https://developer.mozilla.org/en-US/docs/Web/API/History/back))~~

**Comment by Skeletonxf** [comment]
- [x] Update normal duplication
- [x] Update advanced duplication
- [x] Update settings UI
- [x] Update automated dismissing the advanced duplication tab UI
- [x] Update permissions UI in advanced duplication tab
- [x] Test on Firefox for Android to make sure everything still works there
- [x] Delete all the replaced code

**Comment by Skeletonxf** [comment]
Future version
- [ ] Revisit https://github.com/Skeletonxf/duplicate-tab/issues/8 (it may be possible by combining [`executeScript`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/executeScript) with [`history.back()`](https://developer.mozilla.org/en-US/docs/Web/API/History/back))

**Comment by Skeletonxf** [comment]
Closing this issue as the addon is updated to MV3 and all problems with that update are resolved
